name: DiamondBrokeMessage
main: andreiwasfound.diamondbrokemessage.Main
author: AndreiWasFound
version: 4.0
description: Tells every player in the server AND the console that "x" broke a diamond ore. Good for a survival server with friends that may be xrayers :)