name: DiamondBrokeMessage
main: andreiwasfound.diamondbrokemessage.Main
author: AndreiWasFound
version: 5.2
description: Tells every player in the server AND the console that PLAYERNAME broke a diamond ore.

commands:
  diamondbrokemessage:
    description: Reloads DiamondBrokeMessage config
    usage: /diamondbrokemessage reload
    permission: diamondbrokemessage.reload